# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  - main  # Change this branch to match your main development branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      python -m venv myenv
      source myenv/bin/activate
      pip install -r requirements.txt
      python main.py
    displayName: 'Set up Python environment'

  # - script: |
  #     python main.py  # Replace with the name of your Python script
  #   displayName: 'Run Python Application'

